fix: example config matches docs
docs say this should be called `rpc_url`. Running with `rpc_ws` gives:

```
Exception: Missing config param: chain.rpc_url
```

Signed-off-by: Cole Bosmann <cole.bosmann@gmail.com>